version: '3.3'

services:

  crm_db:
    image: mariadb:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
#   restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=api
      - MYSQL_DATABASE=apiDB
      - MYSQL_USER=api
      - MYSQL_PASSWORD=api
      
  frontend:
    image: swaggerapi/swagger-ui
    ports:
      - 3000:8080
    environment:
      - URL=http://localhost:8080/openapi
    depends_on:
      - crm_db

  api-gradle:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-gradle
    ports:
      - 8080:8080
    environment:
      - DB=crm_db
    links:
      - crm_db

  unit-testing:
    build:
      context: .
      dockerfile: test/Dockerfile
    image: unit-testing:latest
    volumes:
      - "./tests-results:/usr/src/app/mochawesome-report/"
    command: /bin/bash wait_for_api-gradle.sh http://api-gradle:8080/health
    depends_on:
      - api-gradle


