# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#

workflows:
  version: 2
  commit:
    jobs:
      - build:
          filters:
            branches:
              only: develop
  nightly:
    triggers:
      - schedule:
          cron: "30 03 * * *"
          filters:
            branches:
              only:
                - develop
    jobs:
      - build

jobs:
  build:
    docker:
     - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run:
          name: Install Gradle Dependencies
          command: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: "Gradle microBundle"
          command: gradle microBundle

      - store_artifacts:
          path: build/libs
    
      #Docker stuff
      - setup_remote_docker
      - run:
          name: "Deploy Database/Frontend/API and run Unit tests"
          command: 'docker-compose -f docker-compose.yml up --build --exit-code-from unit-testing'
          